from .simple_check import ReportSimpleCheck
from .banned_words_in_literature import BannedWordsInLiteratureCheck
from .banned_words_check import ReportBannedWordsCheck
from .page_counter import ReportNumberOfPages
from .image_share_check import ReportImageShareCheck
from .right_words_check import ReportRightWordsCheck
