from .simple_check import ReportSimpleCheck
from .literature_references import ReferencesToLiteratureCheck
from .banned_words_in_literature import BannedWordsInLiteratureCheck
from .banned_words_check import ReportBannedWordsCheck
from .page_counter import ReportNumberOfPages
from .image_share_check import ReportImageShareCheck
from .right_words_check import ReportRightWordsCheck
from .headers_at_page_top_check import ReportHeadersAtPageTopCheck
from .sections_check import ReportSectionCheck
from .style_check_settings import StyleCheckSettings
from .short_sections_check import ReportShortSectionsCheck
from .first_pages_check import ReportNeededPages
from .needed_headers_check import ReportNeededHeaders
from .chapters import ReportHeaders
from .intro import ReportIntroduction
from .main_text_check import ReportMainTextCheck

