version: '2'

services:
  web:
    build: .
    image: slides_checker_base_image
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - worker
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
      - CELERY_BROKER_URL=${REDIS_URL}
      - CELERY_RESULT_BACKEND=${REDIS_URL}
    volumes:
      - ./app:/usr/src/project/app
      - ./db_versioning:/usr/src/project/db_versioning
      - presentation_files:/usr/src/project/files/
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

  worker:
    image: slides_checker_base_image
    restart: always
    command: celery --app=app.tasks.celery worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=${REDIS_URL}
      - CELERY_RESULT_BACKEND=${REDIS_URL}
    depends_on:
      - redis
      - mongodb
    volumes:
      - ./app:/usr/src/project/app
      - presentation_files:/usr/src/project/files/
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

  redis:
    image: redis:6-alpine
    restart: always
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:4.0.17-xenial
    restart: always
    command:
      - '--wiredTigerCacheSizeGB=${MONGODB_CACHE_SIZE:-1}'
    ports:
      - "27017:27017"
    volumes:
      - ../slides_checker_mongo_data:/data/db

  passback_grades:
    image: slides_checker_base_image
    command: python3 ./app/passback_grades.py
    restart: always
    depends_on:
      - mongodb
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

volumes:
  presentation_files:
  redis_data:
  flower_data:
