services:
  web:
    extends:
      file: docker-compose.yml
      service: web
    ports:
      - "8080:8080"
    volumes:
      - ./app:/usr/src/project/app

  worker:
    extends:
      file: docker-compose.yml
      service: worker
    volumes:
      - ./app:/usr/src/project/app

  worker-dashboard:
    extends:
      file: docker-compose.yml
      service: worker-dashboard
    command: celery --broker=${REDIS_URL} flower --port=5555 --persistent=True
    ports:
      - "5555:5555"

  redis:
    extends:
      file: docker-compose.yml
      service: redis

  mongodb:
    extends:
      file: docker-compose.yml
      service: mongodb
    ports:
      - "27017:27017"

volumes:
  files:
  redis_data:
  flower_data:
