FROM python:3.12-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONPATH=/app
ENV TZ=Europe/Moscow

WORKDIR /app

RUN apt update && apt install -y \
    g++ \
    gcc \
    libreoffice-writer \
    libreoffice-impress \
    default-jre \
    libreoffice-java-common \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir pytest pytest-mock pytest-cov pytest-xdist pytest-html

COPY . .

RUN mkdir -p test_results

CMD ["pytest", "-n", "auto", "--html=test_results/report.html", "--self-contained-html", "tests/reports/"]
