ARG IMAGE_VERSION=0.6

FROM python:3.12-slim-bookworm

LABEL project='dis'
LABEL version='worker-base-${IMAGE_VERSION}'

ENV LANG=en_US.UTF-8
ENV TZ=Europe/Moscow

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt update && apt install -y g++ gcc libreoffice-writer libreoffice-impress default-jre libreoffice-java-common
