FROM selenium/standalone-chrome:121.0-chromedriver-121.0-grid-4.18.0-20240220

WORKDIR /usr/src/project

USER root
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    rm -rf /var/lib/apt/lists/*

COPY tests ./tests
RUN pip install -r tests/requirements.txt

CMD ["python3", "tests/main.py", "--login", "admin", "--password", "admin"]
