version: '3.8'

services:
  web:
    build: .
    image: slides_checker_base_image
    restart: always
    ports:
      - "${WEB_PORT:-8080}:8080"
    depends_on:
      - mongodb
      - worker
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
      - CELERY_BROKER_URL=${REDIS_URL}
      - CELERY_RESULT_BACKEND=${REDIS_URL}
    volumes:
      - presentation_files:/usr/src/project/files/
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

  worker:
    image: slides_checker_base_image
    restart: always
    command: celery --app=app.tasks.celery worker -n celery@worker --beat -Q ${CELERY_QUERIES} --loglevel=info
    environment:
      - CELERY_BROKER_URL=${REDIS_URL}
      - CELERY_RESULT_BACKEND=${REDIS_URL}
    depends_on:
      - redis
      - mongodb
    volumes:
      - presentation_files:/usr/src/project/files/
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

  worker-dashboard:
    image: slides_checker_base_image
    command: celery --broker=${REDIS_URL} flower --port=${FLOWER_PORT} --url_prefix=${FLOWER_PREFIX} --basic_auth=${FLOWER_AUTH} --persistent=True
    ports:
      - "${FLOWER_PORT}:5555"
    environment:
      - SECRET_KEY=${FLOWER_SECRET_KEY}
      - CELERY_BROKER=${REDIS_URL}
      - CELERY_BACKEND=${REDIS_URL}
    volumes:
      - flower_data:/etc/db/
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - worker
      - redis

  redis:
    extends:
      file: docker-compose.yml
      service: redis 

  mongodb:
    extends:
      file: docker-compose.yml
      service: mongodb
    ports:
      - "27017:27017"

  selenium-tests:
    build:
      context: .
      dockerfile: Dockerfile_selenium
    environment:
      - LOGIN=${ADMIN_PASSWORD}
      - PASSWORD=${ADMIN_PASSWORD}  
    depends_on:
      - web
    network_mode: service:web

volumes:
  presentation_files:
  redis_data:
  flower_data:

