FROM python:3.12-slim-bullseye

LABEL project='dis'
LABEL version='0.5-base'

ENV LANG=en_US.UTF-8
ENV TZ=Europe/Moscow

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt update && apt install -y g++ gcc libreoffice-writer libreoffice-impress default-jre tesseract-ocr tesseract-ocr-rus

ADD requirements.txt .
RUN python3 -m pip install -r requirements.txt --no-cache-dir
