version: '2'

services:
  web:
    build: .
    image: slides_checker_base_image
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./:/usr/src/project


  worker:
    build: .
    command: celery worker --app=app.tasks.celery --loglevel=info
    volumes:
      - ./:/usr/src/project
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  redis:
    image: redis:6-alpine

  mongodb:
    image: mongo:4.0.17-xenial
    restart: always
    volumes:
      - mongodata:/data/db

  passback_grades:
    image: slides_checker_base_image
    command: python3 ./app/lti_session_passback/passback_grades.py
    restart: always
    depends_on:
      - mongodb

volumes:
  mongodata:
