services:
  selenium-hub:
    image: selenium/hub:4.18.0
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  chrome-node:
    image: selenium/node-chrome:4.18.0
    container_name: chrome-node
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://selenium-hub:4444

  selenium-tests:
    build:
      context: .
      dockerfile: Dockerfile_selenium
    environment:
      - LOGIN=admin
      - PASSWORD=${ADMIN_PASSWORD}
    depends_on:
      - web
      - chrome-node
      - selenium-hub
    network_mode: service:web
