FROM python:3.12-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONPATH=/app
ENV TZ=Europe/Moscow

WORKDIR /app

RUN apt update && apt install -y \
    g++ \
    gcc \
    libreoffice-writer \
    libreoffice-impress \
    default-jre \
    libreoffice-java-common \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir pytest pytest-mock pytest-cov

COPY . .

CMD ["pytest", "tests/reports/"]
