version: '2'

services:
  web:
    build: .
    image: slides_checker_base_image
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - worker
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./app:/usr/src/project/app
      - ./db_versioning:/usr/src/project/db_versioning
      - presentation_files:/usr/src/project/files/
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

  worker:
    image: slides_checker_base_image
    command: celery --app=app.tasks.celery worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - mongodb
    volumes:
      - ./app:/usr/src/project/app
      - presentation_files:/usr/src/project/files/
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

  redis:
    image: redis:6-alpine

  mongodb:
    image: mongo:4.0.17-xenial
    restart: always
    command:
      - '--wiredTigerCacheSizeGB=1'
    ports:
      - 27017:27017
    volumes:
      - ../slides_checker_mongo_data:/data/db

  passback_grades:
    image: slides_checker_base_image
    command: python3 ./app/passback_grades.py
    restart: always
    depends_on:
      - mongodb
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

volumes:
  presentation_files:
