ARG IMAGE_VERSION=0.6

FROM dvivanov/dis:worker-base-${IMAGE_VERSION}

LABEL project='dis'
LABEL version='worker-image-${IMAGE_VERSION}'

ENV PYTHONPATH="${PYTHONPATH}:/usr/src/project/app"

WORKDIR /usr/src/project

COPY requirements.txt .
RUN python3 -m pip install -r requirements.txt --no-cache-dir

COPY . .
