# `ruff format` uses: line-length, indent-width, and [format] block.
# `ruff check` uses: [lint] block.

target-version = "py312"
line-length = 88 # Black default
indent-width = 4

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[lint]
select = [
  "E",   # pycodestyle errors (PEP8)
  "W",   # pycodestyle warnings
  "F",   # pyflakes (unused imports/names, undefined names, etc.)
  "I",   # isort (import order)
  "B",   # flake8-bugbear (likely bugs / risky patterns)
  "SIM", # simplify expressions
]

ignore = ["E501"] # line too long
