version: '2.1'
services:
    sut:
        build:
            context: .
            dockerfile: Dockerfile.test
        command: pytest /app/templater/tests.py -s
        healthcheck:
            test: ["CMD", "curl", "-f", "http://web:5000"]
            interval: 30s
            timeout: 10s
            retries: 5
        links:
            - web
    web:
        build:
            context: .
            dockerfile: Dockerfile
        #command: python3 -u runapp.py
        command: >
            sh -c "sed -i 's/let recaptcha_site_key = .*/let recaptcha_site_key = \"6LebQMgZAAAAAOqpNojsAdJIanme__SYR-H4Z2V-\"/' /app/templater/static/js/main.js &&
                sed -i 's/recaptcha_key = .*/recaptcha_key = 6LebQMgZAAAAAOcwhzOtpnxYtfeVP1B11FB30Cc1/' /app/config.ini &&
                sed -i 's/RECAPTCHA_SITE_KEY/6LebQMgZAAAAAOqpNojsAdJIanme__SYR-H4Z2V-/' /app/templater/templates/layout.jinja2 &&
                python3 -u runapp.py"
        #logging:
        #    driver: "none"
        #ports:
        #    - "5000:5000"
        links:
            - db
    db:
        image: mongo:3.6
        #logging:
        #    driver: "none"