[loggers]
keys=root

[handlers]
keys=consoleHandler

[formatters]
keys=detailedFormatter

[logger_root]
level=DEBUG
handlers=consoleHandler

[handler_consoleHandler]
class=StreamHandler
level=INFO
formatter=detailedFormatter
args=(sys.stdout,)

[formatter_detailedFormatter]
# class=check_log_context.CheckContextFormatter
format=%(levelname)-8s [%(asctime)s.%(msecs)03d] %(module)s:%(lineno)d %(funcName)s() - %(message)s
datefmt=%Y-%m-%d %H:%M:%S
