def includeme(config):
    config.add_static_view('static/css', 'static/css')
    config.add_static_view('static/js', 'static/js')
    config.add_static_view('static/img', 'static/img')
    config.add_static_view('ViewerJS', 'static/ViewerJS')

    config.add_route('captcha', '/')
    config.add_route('home', '/home')
    config.add_route('upload', '/upload')
    config.add_route('files', '/files')
    config.add_route('verify', '/verify')
    config.add_route('render', '/render')
    config.add_route('locale', '/locale')
    config.add_route('preview_file', '/preview')
    config.add_route('api_data_files', '/api/data-files')
    config.add_route('api_templates', '/api/templates')

    config.add_route('templates', '/templates')
    config.add_route('edit_template', '/edit_template/{template_id}')
    config.add_route('delete_template', '/delete_template/{template_id}')
    config.add_route('delete_templates', '/delete_templates')
    config.add_route('add_template', '/add_template')
    config.add_route('api_update_template', '/api/update_template/{template_id}')
    config.add_route('api_add_template', '/api/add_template')
    config.add_route('export_template', '/export_template/{template_id}')
    config.add_route('oauth_callback', '/oauth_callback')
    config.add_route('start_auth', '/start_auth')
    config.add_route('dis_redirect', '/dis')
    config.add_route('input_template_data', '/input_template_data/{template_id}')
    config.add_route('api_save_template_data', '/api/save_template_data/{template_id}')
    config.add_route('api_get_template_data_status', '/api/get_template_data_status/{template_id}')
    config.add_route('export_archive_to_drive', '/export_archive_to_drive')
    config.add_route('user_home', '/user_home')

