from .find_def_sld import FindDefSld
from .find_tasks import FindTasks
from .further_dev import FurtherDev
from .search_keyword import SearchKeyWord
from .sld_enum import SldEnumCheck
from .sld_num import SldNumCheck
from .sld_similarity import SldSimilarity
from .template_name import TemplateNameCheck
from .title_format import TitleFormatCheck
from .pres_right_words import PresRightWordsCheck
from .image_share import PresImageShareCheck
from .banned_words import PresBannedWordsCheck
from .empty_slide_check import PresEmptySlideCheck
