from .find_def_sld import FindDefSld
from .find_tasks import FindTasks
from .further_dev import FurtherDev
from .search_keyword import SearchKeyWord
from .sld_enum import SldEnumCheck
from .sld_num import SldNumCheck
from .sld_similarity import SldSimilarity
from .template_name import PresTemplateNameCheck
from .title_format import TitleFormatCheck
from .pres_right_words import PresRightWordsCheck
from .image_share import PresImageShareCheck
from .banned_words import PresBannedWordsCheck
from .find_theme_in_pres import FindThemeInPres
from .verify_git_link import PresVerifyGitLinkCheck
from .empty_slide_check import PresEmptySlideCheck
from .slide_headers_duplication_check import SlideHeadersDuplicationCheck
from .name_of_image_check import PresImageCaptureCheck
from .task_tracker import TaskTracker
from .overview_in_tasks import OverviewInTasks
from .was_were_check import PresWasWereCheck
