name: CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Build system images (non-pulling)
        run: |
          cp .env_example .env
          make build-all
      - name: Run docker-compose
        run: |
          make full-up-d
          sleep 10
      - name: Run tests
        run: |
          curl http://localhost:8080
          curl http://localhost:5555
      - name: Check logs 
        run: docker compose -f docker-compose.yml -f lt_docker/docker-compose.yaml -f docker-compose-selenium.yml logs
        if: always()