name: 'Check for merge conflicts'

on:
  push:
    branches:
      - master

jobs:
  triage:
    runs-on: ubuntu-20.04

    steps:
      - uses: mschilde/auto-label-merge-conflicts@master
        with:
          CONFLICT_LABEL_NAME: "has conflicts"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_RETRIES: 5
          WAIT_MS: 5000