name: Selenium_tests

on: [push]

jobs:
  check_tests:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Build and run docker compose with docker-compose-selenium (tests)
        run: |
          cp .env_example .env
          cp app/VERSION_example.json app/VERSION.json
          make tests
      
      - name: Run check tests (tests)
        run: |
          bash ./tests/scripts/docker_check_tests.sh
